name: workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
        - uses: actions
        - name: a
          run: "make setup"
          uses: owner/repo@ref
        - name: b
          run: "make lint"
          needs: a
          uses: owner/repo@ref
        - name: c
          run: "make test"
          needs: a
          uses: owner/repo@ref
t
