name: workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
        - uses: actions/checkout@v2
        - name: setup node.js 13
          uses: actions/setup-node@v3
          with:
            node-version: '13'
        - name: setup
          run: make setup
        - name: lint
          run: make lint
        - name: test
          run: make test
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
