name: workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
        - uses: actions
        - name: run setup
            run: "make setup; make start"
        - name: run linter
            run: "sh make lint"
        - name: run tests
            run: "sh make test"
